export enum STATUS {
	IDLE = 'idle',
	PAUSE = 'PAUSE',
	READY = 'READY',
	READY_TO_MOVE_UP = 'READY_TO_MOVE_UP',
	READY_TO_MOVE_DOWN = 'READY_TO_MOVE_DOWN',
	MOVING_UP = 'MOVING_UP',
	MOVING_DOWN = 'MOVING_DOWN',
	WAITING = 'waiting',
	PICKED_UP = 'picked-up',
	DROPPED = 'dropped',
}
